### ISSUE TITLE
Feature Request - back-to-top button

### ISSUE THREAD

**Issue by imfing** [imfing/hextra#100]
### Discussed in https://github.com/imfing/hextra/discussions/97

<div type='discussions-op-text'>

<sup>Originally posted by **iju707** September 27, 2023</sup>
Having a back-to-top button would be very helpful in long-form content.
I think it would be better if it is located at the bottom right.</div>

**Comment by remysheppard** [comment]
I can handle this, if you want

**Comment by imfing** [comment]
> I can handle this, if you want

It would be great if you could help with it. 

I expect a similar look and feel as the [nextjs](https://nextjs.org/docs)/[nextra](https://nextra.site/docs/guide/markdown) with no third-party dependencies. Are you able to handle it? @remysheppard

**Comment by remysheppard** [comment]
No problem! Give me a day or two to work in it.

**Comment by imfing** [comment]
thanks, take your time 🙏
I'll assign this ticket to you, feel free to send a draft PR and continue working on there. Let me know if you have any questions setting up the dev environment.

**Comment by imfing** [comment]
Implemented in #105
