### ISSUE TITLE
Logic issue

### ISSUE THREAD

**Issue by bep** [imfing/hextra#108]
https://github.com/imfing/hextra/blob/2df3c563bf343afa1b933decdeb1082417ee335b/layouts/_default/baseof.html#L7

The left side of the above will be falsy if a user disables footer (enable=false) which will make it default to true...

For features that's default on it's easier to use a `disable` option, I think.

Great looking theme.

**Comment by imfing** [comment]
Thank you for bringing this to my attention! 

The use of `enable` was mainly to maintain consistency across the configuration options. And I do agree that `disable` is much better for features that's default `true`.

For now, I could do a `nil` check for the `enable` flag. In the future, I'll consider switching to `disable` flag.
