### ISSUE TITLE
Optimize search feature

### ISSUE THREAD

**Issue by thang-qt** [imfing/hextra#109]
Hi.
I'm trying to build a knowledge sharing site. I'm testing with about 4000 pages and my machine would crash instantly if I try to search even it's a really fast one. Is there anyway to optimize search speed or config alternative search engine?

**Comment by remysheppard** [comment]
Are you saying that you're running Hextra, building out 4,000 pages, trying to search, and it **is in fact crashing**? 

Or are you saying you _assume_ it would crash?

Also, an application of that size, you might actually be better off with a database solution than a static site.

**Comment by imfing** [comment]
It would be nice if you could share your repository in public, so I could figure out what's really going on.

I think 4000 pages definitely gonna overload the local search feature in Hextra.
Hextra pre-computes the search index file and when you open the search, the website load it on-the-fly. 4000 pages would result in very large index file including **all the contents**, thus the browsers or the search library just couldn't handle it. 

In this case, I think integrating with third-party cloud offerings such as [Algolia](https://www.algolia.com/) or [Google Custom Search](https://programmablesearchengine.google.com/) might be a better choice.
