### ISSUE TITLE
Feature Request: Display tags in the List of Blog Posts

### ISSUE THREAD

**Issue by saurabh-mish** [imfing/hextra#128]
Feature request: Tags associated with a post could be displayed above the date when listing all posts.

**Comment by imfing** [comment]
Thanks, this would be a nice feature 👍🏼 because at the moment the blog section is fairly simple and not very feature-rich

**Comment by imfing** [comment]
WIP, is this what you were looking for? 👀 

![](https://user-images.githubusercontent.com/5097752/278775737-c7172a6f-a867-4c93-8a0a-cb99873083a6.png)

Note: currently we can't click those tags to filter by a single tag.

**Comment by saurabh-mish** [comment]
Yes, that looks really good!
