### ISSUE TITLE
Feature to disable/enable dark/light mode switch or enforece only one of them as a default

### ISSUE THREAD

**Issue by pentago** [imfing/hextra#135]
**Feature Description**

I'd like a feature like `light-mode-switch: false` and/or `dark-mode: false` to control whether a user can toggle the dark mode and/or to enforce only light mode as default while hiding the mode toggle.

I prefer the site to be seen in light mode and don't want to use dark mode as a default.

**Comment by imfing** [comment]
Thanks, I will add a flag for switching the behavior in the next release hopefully

**Comment by imfing** [comment]
@pentago FYI, this feature has been implemented in #146 

please wait for the next release to reflect this change, or you could `hugo mod get -u github.com/imfing/hextra@main` to get the latest main branch version.

**Comment by pentago** [comment]
Great work, it worked great! Thanks! <3
