### ISSUE TITLE
Blog and About Headings have Different Size and Line Breaks

### ISSUE THREAD

**Issue by saurabh-mish** [imfing/hextra#15]
The "Blog" heading [on this page](https://imfing.github.io/hextra/blog/) appears to be in H1, and the "About" heading [on this page](https://imfing.github.io/hextra/about/) appears to be H2 and have a additional line break. 

This can be noticed when switching between these pages.

**Comment by imfing** [comment]
I see, will figure out how to minimize the differences between these two pages.
