### ISSUE TITLE
Diagrams Page Takes a Long Time To Load On Slower Connections

### ISSUE THREAD

**Issue by saurabh-mish** [imfing/hextra#16]
On slower internet connections, the [diagrams page](https://imfing.github.io/hextra/docs/guide/diagrams/) takes a lot longer to load than other pages.

**Comment by imfing** [comment]
This is expected. The diagrams page needs Mermaid.js to render the diagrams. It is about several kilobytes but definitely would take longer under a slower connection environment

**Comment by saurabh-mish** [comment]
There's a local minified `mermaid.min.js` that's being used.

**Comment by imfing** [comment]
> There's a local minified `mermaid.min.js` that's being used. 

Yes, in the future we might want this configurable so people can use CDNs for diagrams and math formulas
