### ISSUE TITLE
Sidebar disappears if I chang the name of directory "docs"

### ISSUE THREAD

**Issue by mobilephone724** [imfing/hextra#165]
**Description**

Hello everyone, I have changed my hugo's theme to `hextra` but the issue still bothers me.
**Steps To Reproduce**

1.  start hugo server with the examplesite `cd exampleSite && hugo server  -t ../..`
2. copy to a new directory `cp -r content/docs content/docs_2`
3. open "localhost:${port}/docs_2/guide/organize-files/"
4. the sidebar disappears

**Expected Behavior**

Should the page be same as `docs/guide/organize-files/` ?

**Actual Behavior**

Sidebar disappears 

**Screenshots**
<img width="1728" alt="image" src="https://github.com/imfing/hextra/assets/52440537/32bb218a-26b5-4bf8-b9a2-51719177d934">
<img width="1698" alt="image" src="https://github.com/imfing/hextra/assets/52440537/f279bae4-1a83-4fc2-b213-104ebb14182d">

**Environment**

* hugo: v0.118.2
* Browser: edge
* OS: macos arm64
* theme version: latest

**Additional Context**
* Should the sidebar behave the same in different subdirs `content/${subdirs}` but the `docs` directory has something special?
* Or do I ignore something in official docs? But I have searched the "sidebar" keyword almost everywhere.

Best wishes!

**Comment by imfing** [comment]
@mobilephone724 

By default, other pages won't automatically apply the `docs` section style.

You can apply the `docs` layout to other sections, for example `docs_2`, by:

https://github.com/imfing/hextra/discussions/18#discussioncomment-7184645

**Comment by imfing** [comment]
I will update the documentation for better clarification on this.

**Comment by imfing** [comment]
I've added a section for the layout options in documentation, please check it out:
https://imfing.github.io/hextra/docs/guide/organize-files/#layouts

**Comment by mobilephone724** [comment]
Thanks so much!

**Comment by imfing** [comment]
> @imfing The issue persists despite adding `layout: docs` to an .md in a non /docs folder. Built on exampleSite. No problem using docs as the folder name.

@reavpC6K did you use this

```yaml
---
title: My Docs
cascade:
  type: docs
---

```

https://imfing.github.io/hextra/docs/guide/organize-files/#layouts
