### ISSUE TITLE
Increase opacity of code copy button

### ISSUE THREAD

**Issue by c2tz** [imfing/hextra#182]
**Feature Description**

Increase opacity of code copy button for better accessibility

**Problem/Solution**

Better readability of the button's copy icon.

<img width="332" alt="chrome_D2dn7hxyY2" src="https://github.com/imfing/hextra/assets/95414249/b1b40d66-d4d0-4144-b6fb-9820af86c9fa">

**Alternatives Considered**

No

**Additional Context**

Using the github copy button as a base, but it has an opacity of 0, which I don't think is necessary. Just increasing the opacity is desirable, but it should also be possible to see through the button, or else add a blur effect.

**Comment by imfing** [comment]
@c2tz thank you! this has been fixed in #185
