### ISSUE TITLE
"&" rendered as "&amp;" in ToC

### ISSUE THREAD

**Issue by saurabh-mish** [imfing/hextra#188]
**Description**

The character "&" is rendered as "&amp;" in the ToC section.

**Steps To Reproduce**

1. Set `toc: true` in the front matter of the markdown file.
2. Create a heading (`##`) containing text "&". Example "## Implementation & Tests"
3. Run `hugo server --buildDrafts --disableFastRender --ignoreCache`

**Expected Behavior**

"Implementation & Tests" to be displayed on the right side in the ToC.

**Actual Behavior**

"Implementation \&amp; Tests" is being displayed

**Screenshots**

<img width="389" alt="Screenshot 2023-11-04 at 5 28 16 PM" src="https://github.com/imfing/hextra/assets/52619598/a5ba78bf-abf9-4434-82de-3b194199505d">

**Environment**

- Hugo Version: [e.g., 0.85.0]
- Browser/OS: [e.g., Chrome, MacOS]
- Theme Version: [e.g., v2.0]

**Additional Context**

**Comment by imfing** [comment]
This PR #190 should fix this issue:

![image](https://github.com/imfing/hextra/assets/5097752/327d17bc-e9f3-40a5-acbe-e14f7c160855)
