### ISSUE TITLE
Apostrophe Not Rendered Correctly in ToC

### ISSUE THREAD

**Issue by saurabh-mish** [imfing/hextra#19]
Headings containing apostrophe ' dont rendered correctly under "On this page".

Example:

<img width="1059" alt="Screenshot 2023-08-31 at 4 10 30 PM" src="https://github.com/imfing/hextra/assets/52619598/2484139f-ac8e-43b8-bfec-6477d6ebdcf7">

**Comment by imfing** [comment]
@saurabh-mish this should be fixed by #20 

I've cut a new release https://github.com/imfing/hextra/releases/tag/v0.2.3

Please upgrade via `hugo mod get -u`
