### ISSUE TITLE
Local front matter editURL not functionning and breaks rendering

### ISSUE THREAD

**Issue by davidovich** [imfing/hextra#194]
**Description**

When specifying a local editURL in front-mater, the page fails to render because we use a [`with` clause](https://github.com/imfing/hextra/blob/main/layouts/partials/toc.html#L30) to set the user defined URL. But inside the `{{ with }}` the context is `.`, not `.Params.editURL`.

**Steps To Reproduce**

1. In front matter, specify `editURL: http://myurl`

**Expected Behavior**

`editURL` is correctly set and is used to render the editURL 

**Actual Behavior**

Render fails with:

```
template failed at <partial "toc.html" .>: error calling partial: 
"[root_path]/_vendor/github.com/imfing/hextra/layouts/partials/toc.html:30:55": 
execute of template failed at <.Params.editURL>: can’t evaluate field Params in type string
```

Replacing 

```
      {{- with .Params.editURL -}}{{ $editURL = .Params.editURL }}{{- end -}}
```

With

```
      {{- with .Params.editURL -}}{{ $editURL = . }}{{- end -}}
```

Fixes the bug.

**Comment by imfing** [comment]
@davidovich thank you for spotting this. it's been fixed in #195
