### ISSUE TITLE
When copying the code block in {{% details %}}, the default is the first code block in this article

### ISSUE THREAD

**Issue by liyangxia** [imfing/hextra#200]
**Description**

Question page: [Getting Started](https://imfing.github.io/hextra/docs/getting-started/)

When copying `hugo mod get -u` in `{{% details title="How to update theme?" %}}`, the actual copied content is `$ hugo new site my-site --format=yaml`

When copying `hugo mod get -u github.com/imfing/hextra`, it corresponds to the second code block of this document `# initialize hugo module...`

**Steps To Reproduce**

1. View the [Getting Started](https://imfing.github.io/hextra/docs/getting-started/) page
2. Copy code in "How to update theme?" details
3. Paste the duplicate anywhere

**Expected Behavior**

Correctly copy code blocks

**Actual Behavior**

When you copy the code block in `{{% details %}}`, what is actually copied is the content of the first code block in this article

**Screenshots**

<img width="1512" alt="Screenshot 2023-11-12 at 01 24 49" src="https://github.com/imfing/hextra/assets/126838514/f91d4a81-2fa4-4634-b37b-935dbacfb26c">

<img width="1512" alt="Screenshot 2023-11-12 at 01 25 00" src="https://github.com/imfing/hextra/assets/126838514/fdeadda7-b275-451e-818f-8be4ef64cac5">

**Environment**

*Official sample document*

- Hugo Version: Not sure
- Browser/OS: [Chrome, MacOS]
- Theme Version: Not sure

**Additional Context**

There is no reproduction in the page [Deploy Site](https://imfing.github.io/hextra/docs/guide/deploy-site/). Is it because there is only `{{% details %}}` without ordinary code blocks?

**Comment by imfing** [comment]
@liyangxia thanks, I'll look into this

**Comment by imfing** [comment]
it appears that within the `details` shortcode, the rendering of code blocks was resetting their ordinal numbers to 0. This caused the ids to be conflicted. thus when the code copy button was clicked, it was referencing these duplicate IDs, resulting in the observed bug.

https://github.com/imfing/hextra/blob/8801a04ebe4ff62a88a2ba2b9974eba3698f9b29/layouts/_default/_markup/render-codeblock.html#L21

**Comment by imfing** [comment]
thanks, it's fixed in #201
