### ISSUE TITLE
Typos in /layouts/partials/sidebar.html

### ISSUE THREAD

**Issue by OliverWu515** [imfing/hextra#202]
**Description**

Typos are found in line 156 and line 167 of /layouts/partials/sidebar.html. Two 'sidebar' are wrongly written as 'sidebear'.
They have no influence on generating web pages, but I think typos may lead to errors in the future development:)

**Screenshots**
They 're highlighted in the picture below.
![image](https://github.com/imfing/hextra/assets/123916865/26100328-571d-472b-8e86-fc08828eebc1)

**Comment by imfing** [comment]
Fixed in #203
