### ISSUE TITLE
Better search bar aesthetics.

### ISSUE THREAD

**Issue by c2tz** [imfing/hextra#210]
**Feature Description**

Better search bar aesthetics.

**Problem/Solution**

Deletion of the cross, which deletes whole words (of little interest, breaks the aesthetics of the CTRL+K rectangle and is not visible in clear mode).

**Alternatives Considered**

Add a shortcode to disable it for those who want it, or shift it further to the left. But in this case you must prevent the text from passing underneath (which is currently the case for the CTRL+K rectangle). see below

![chrome_GDyDaj5IVI](https://github.com/imfing/hextra/assets/95414249/2856c1f2-cc19-42d3-811c-33aa18a8bad7)

**Additional Context**

![chrome_iGzUVuuzqX](https://github.com/imfing/hextra/assets/95414249/339aded8-ef98-4ffe-98f3-a28186ac2be9)
---
![chrome_FdFFO69BxW](https://github.com/imfing/hextra/assets/95414249/968b327f-e787-4c6f-8cab-28aa3056eb1d)

**Comment by c2tz** [comment]
here's an example of a search bar that matches what I'm imagining : https://cobe.vercel.app/

**Comment by imfing** [comment]
> here's an example of a search bar that matches what I'm imagining : [cobe.vercel.app](https://cobe.vercel.app/)

Thanks for the feedback. I'll update the search bar to align with this example.
