### ISSUE TITLE
bolg页面分页导航、自定义copyright选项等

### ISSUE THREAD

**Issue by zhenplus** [imfing/hextra#220]
您好，我在使用0.7.0版本，有几个问题
1.type bolg页面没有分页导航，或有的话该如何启用
2.fotter中的copyright信息没有自定义选项，亦或您没有在docs中说明
3.在hugo.yaml中开启comments后，about、_index等页面front matter中的comments: false 无法关闭该页面comments模板生成

感谢回复

**Comment by imfing** [comment]
> Hello, I am using version 0.7.0 and have several questions
> 1. Type bolg page does not have paging navigation, or if so, how to enable it?
> 2. The copyright information in fotter has no customization options, or you did not explain it in the docs
> 3. After opening comments in hugo.yaml, comments: false in the front matter of pages such as about and _index cannot turn off the generation of comments templates for this page.

1. unfortunately pagination has not been supported yet
2. please see the doc here: https://imfing.github.io/hextra/docs/guide/configuration/#footer I guess you were referring to the Chinese translation of it which may not be up-to-date. 
3. i will look into that.

**Comment by Dysheng** [comment]
Powered By 无法修改吗？

**Comment by imfing** [comment]
@Dysheng please use the following i18n key to override: 

https://github.com/imfing/hextra/blob/7772313a53c41d1c70a1b9ad1a39d3680b141e13/i18n/zh-cn.yaml#L11
