### ISSUE TITLE
No style for definition lists

### ISSUE THREAD

**Issue by billux** [imfing/hextra#223]
**Feature Description**

There is currently to specific CSS rules applied to definition lists in hextra theme, so they appear like raw text.

It would be nice to have some basic styling applied to them.

**Problem/Solution**

I put these rules in my `custom.css`, inspired from `ul` and `ol` rules, but it sure can be improved:
```css
/*
 * Style definition lists.
 */
.content :where(dl):not(:where([class~="not-prose"], [class~="not-prose"] *)) {
	margin-top: 1.5rem;
}
.content :where(dl):not(:where([class~="not-prose"], [class~="not-prose"] *)) dt {
	margin-top: 0.7rem;
	margin-bottom: 0.5rem;
}
.content :where(dl):not(:where([class~="not-prose"], [class~="not-prose"] *)) dd {
	margin-top: 0.5rem;
	margin-bottom: 0.5rem;
    margin-left: 1.5rem;
}

**Comment by imfing** [comment]
Hi, which markdown syntax are you using to create content with `definition lists`? are you using raw HTML such as `<dl>`?

**Comment by billux** [comment]
I use [goldmark](https://github.com/yuin/goldmark/) which is the default markdown processor in Hugo, with no special configuration.

The markdown looks like:
```markdown
Term one
: Here is the text explaining term one.

Term two
: Here is the text explaining term two.
```

And Hugo generates the following HTML:
```html
<dl>
<dt>Term one</dt>
<dd>Here is the text explaining term one.</dd>
<dt>Term two</dt>
<dd>Here is the text explaining term two.</dd>
</dl>
```
