### ISSUE TITLE
Generated edit link won't contain the path of i18n folder under ./content folder

### ISSUE THREAD

**Issue by librehugohu** [imfing/hextra#228]
**Description**

Hextra seems won't add i18n folder path properly if user set hugo.yaml/editURL option as usual and manage translation by content directory

**Steps To Reproduce**

1. Set i18n in hugo.yaml and add some i18n folder in ./content folder
2. Set editURL option end with "/edit/main/content"
3. Deplopy

**Expected Behavior**

> The edit links will be automatically generated for each page based on the provided url as root directory.

According to hextra doc, the edit link address will contain the i18n folder under "./content" folder, for example, if we have such folder structure:

![image](https://github.com/imfing/hextra/assets/51823222/8583cccd-549a-43ba-97f6-22150ec4e8f0)

The "zh-CN/" will be add into edit link address of each pages under "./content/zh-CN/" folder, it should be a part of generated url, not a part of provided base url.

**Actual Behavior**

Actually, after deployment we can see the edit link of page ".../main/content/zh-CN/about/_index.md" will be ".../edit/main/content/about/_index.md", github will show 404 page.

**Screenshots**

![image](https://github.com/imfing/hextra/assets/51823222/11f1d522-0ce2-42c9-ade0-7f95bbbf3a78)

**Environment**

- Hugo Version: v0.121.0
- Browser/OS: latest Chrome on Windows 11
- Theme Version: v0.7.0

**Additional Context**

**Comment by imfing** [comment]
thanks. 

it looks like the `.File` does not handle the multi-lang case automatically. will fix it

**Comment by dogweather** [comment]
Thanks! I just had this too.
