### ISSUE TITLE
Lists with inline code elements and nested lists have extra margin.

### ISSUE THREAD

**Issue by franknorton** [imfing/hextra#229]
**Description**

When creating a list with inline code elements you get uneven spacing if the next element in the list is a list itself. 

**Steps To Reproduce**

Create a list with the following structure in markdown to see the problem.

```markdown
- `Inline code element`
    - Next element, too much spacing above this.
    - Spacing is fine here.
```

The resulting HTML looks like:
```html
<ul>
  <li>
    <code>Inline code element</code>
    <ul>
      <li>Next element, too much spacing</li>
      <li>Spacing is fine here.</li>
    </ul>
  </li>
</ul>
```

**Expected Behavior**

The spacing should've zeroed out the margin-top like it does for normal nested lists.

![image](https://github.com/imfing/hextra/assets/1672772/c834a818-88be-454a-a248-b5040f46e2bb)

This CSS does the zeroing: 
```css
.content :where(ul):not(:where([class~=not-prose],[class~=not-prose] *)):first-child {
    margin-top: 0px;
}
```

**Actual Behavior**

![image](https://github.com/imfing/hextra/assets/1672772/c913758c-9b25-4fe6-aca5-ad70386e000c)

The previous css is excluded, I believe because the `ul` is no longer the `first-child` of the containing `li`, the `code` tag is getting in the way.

**Additional Context**

This problem occurs with other elements besides `<code>`, such as when italicizing an element (`<em>`) or bolding it (`<strong>`)

**Environment**

- Hugo Version: 0.121.1
- Browser/OS: Vivaldi, Windows 11
- Theme Version: v0.7.0

**Comment by imfing** [comment]
thanks, will take a look
