### ISSUE TITLE
Giscus widget refused  to connect. May be a bug of the method hextra deal with i18n folder.

### ISSUE THREAD

**Issue by librehugohu** [imfing/hextra#231]
You will get more basic info in issue #228. Today I found another bug about i18n folder and giscus.

As #228 showed, I use i18n folder to manage i18n markdown files, now every files is under `./content/zh-CN` folder(I haven't write texts in English or French, but I want to setup i18n folder structure firstly). Besides I configured giscus properly, but the giscus widget can't be loaded. 

![image](https://github.com/imfing/hextra/assets/51823222/c968d382-c4b8-410f-80eb-16b8c5a71f98)

After check Network tab of Dev tools of Chrome, we can see this result.

![image](https://github.com/imfing/hextra/assets/51823222/903de97a-42a7-4835-9bf6-6ca08c18799f)

The requested URL begins with `https://giscus.app/zh-cn/widget?origin=`, I tried to remove `zh-cn/` from URL, then the giscus widget can be accessed. Inspired by this discovery, I disabled i18n configs in `./hugo.yaml` and removed i18n folders under `./content` path, the loaded giscus widget proved my guess.

So I think hextra may doesn't consider interactions between i18n folder and other functions of hextra.

You can see these bugs in [my blog](https://librehugohu.github.io/) and find code from [blog repos](https://github.com/librehugohu/librehugohu.github.io).

**Comment by imfing** [comment]
Thanks for reporting, I will look into this

**Comment by imfing** [comment]
I wasn't able to reproduce this issue:

![image](https://github.com/imfing/hextra/assets/5097752/5199e13c-16f3-4c04-b8a3-e429e58eac94)

Could you provide more details?

**Comment by librehugohu** [comment]
I noticed that your Request URL contains `zh-CN`, while mine is `zh-cn`. The Giscus widget will returns 404 with `zh-cn` but works correctly with `zh-CN`.

I don't understand why.

**Comment by imfing** [comment]
@librehugohu did you set the lang code like:

https://github.com/imfing/hextra/blob/7191e259584e339b499a63e2e60cb6d818222e18/exampleSite/hugo.yaml#L27

**Comment by librehugohu** [comment]
Oops, I didn't. Giscus widget appears after setting this option.
