### ISSUE TITLE
Enhance style of inline code block

### ISSUE THREAD

**Issue by librehugohu** [imfing/hextra#233]
This is the style of `inline code block` of hextra:

![image](https://github.com/imfing/hextra/assets/51823222/54813865-0044-4568-a458-fd90bdda1e9d)

That's how it look like in whole page:

![image](https://github.com/imfing/hextra/assets/51823222/9d5b0f58-2e3e-461b-8424-c43e2cc1a448)

Its background color is similar to page's background color and without a clear border, I worry readers won't distinguish inline code block rapidly in long pages of text.

I hope you can do some improvement, like the style of Docusaurus:

![image](https://github.com/imfing/hextra/assets/51823222/3af350e7-75c5-4731-aa80-ec272126e632)

**Comment by imfing** [comment]
Hi, thanks for creating the issue!
You could always use the custom CSS to tweak the elements' appearance in the theme.

I couldn't think of a solid reason to add borders to the code elements. GitHub is not doing this either:

<img width="856" alt="image" src="https://github.com/imfing/hextra/assets/5097752/0d0b334b-339e-44ab-bdb9-334bc5c9bdee">

**Comment by librehugohu** [comment]
Yes, you are right. I can use custom css to set code-block's background-color, forgot it...sry:(
