### ISSUE TITLE
Active Version Switching

### ISSUE THREAD

**Issue by Lionoca** [imfing/hextra#235]
**Feature Description**

Implementing Hugo for a project that has **multiple versions** that are currently (active) supported we need to:
- allow the users to be able to switch documentation versions to match the project version they are using.

NOTE: As a messy work around, we are using the multi-language switch however this is a limited solution. 

**Problem/Solution**

1. For software that has several _deployed_ versions that are supported, users need to be able to alternate versions. 
2. For a _framework_ for example, compatibility is an issue. Software developed using a previous version of the framework will only be compatible with THAT specific version.
3. Even though the framework has a newer version, software already developed with previous versions of that framework will only be able to be iterated based on that previous version.

A possible solution concept is to allow for several published versions of the article or section to be available. Default version is the most recently published version.

**Alternatives Considered**

As mentioned above, the multi-language capability is being used as a workaround.

**Additional Context**

**Comment by imfing** [comment]
Thanks for putting the details in the issue.
The same issue is being discussed in #224 I'll close this issue and let's move the discussion over there.

> NOTE: As a messy work around, we are using the multi-language switch however this is a limited solution.

I don't recommend this. Instead I recommend using Git (GitHub) to version your previous site sources and publish to different sites. Point back to these previous versions in your latest version site. See discussion in #224  for more details
