### ISSUE TITLE
Blog post at 2024-12-30 disappears

### ISSUE THREAD

**Issue by xiln7** [imfing/hextra#263]
**Description**

Today I post a new blog on our website, of which the date is `2024-12-30`. But when I built the website I found that it just disappeared.

**Steps To Reproduce**

1.  Find any blog post.
2.  Changes its date to '2024-12-30'
3.  Run `hugo server`

**Expected Behavior**

Expect as normal post

**Actual Behavior**

The date fails to be recognized and the post is moved to the bottom to our page

**Screenshots**

None, because it disappears.

**Environment**

- Hugo Version: 0.120.3
- Browser/OS: Safari, MacOS
- Theme Version: latest

**Additional Context**

Knowing that the maintainer may be busy, we will help investigate it if possible. But may need some instructions or hint.

**Comment by imfing** [comment]
@xiln7 Hi, I think you need to use the `--buildFuture` flag to include a post with a future date.

See: https://gohugo.io/getting-started/usage/#draft-future-and-expired-content

**Comment by xiln7** [comment]
Yes, I notice that. Thanks for your reply.
