### ISSUE TITLE
Nested list: <ul> margin-top with bold first element

### ISSUE THREAD

**Issue by davlgd** [imfing/hextra#277]
**Description**

As mentionned in #229 there is an issue in nested list rendering. The 0.7.2 fix wasn't complete, as it doesn't solve the problem when there are multiple nested lists. 

**Steps To Reproduce**

1. Create a nested list in a page
2. Put bold on first-level elements of the list
3. Serve

For example: 

```
- **List 1** 
  - Item 1
  - Item 1 
- **List 2**
  - Item 1
  - Item 2
- **List 3**
  - Item 1
  - Item 2 
``` 

**Screenshots**

As you can see below, `margin-top` is too high (`1.5em`) even with Hextra 0.7.2, only first element is rendered right. On the contrary a `margin-bottom` could be nice:

<img width="685" alt="image" src="https://github.com/imfing/hextra/assets/1110600/1f833b40-a09d-4c06-b472-248a93cac966">

If I replace `margin-top: 1.5em` by `margin-bottom: 1.5em` in inspect dev mode result seems better:

<img width="796" alt="image" src="https://github.com/CleverCloud/documentation/assets/1110600/59a6b48d-60c8-4579-8107-f4834b921742">

**Environment**

- Hugo Version: [0.7.2]
- Browser/OS: [Brave, Safari, macOS]
- Theme Version: [e.g., v2.0]

**Additional Context**

**Comment by imfing** [comment]
hi thanks for creating this issue.

we might need to update the CSS rule in my previous PR

https://github.com/imfing/hextra/pull/276

to 

```css
:where(ul, ol) > li > :where(ul, ol):not(:where([class~=not-prose], [class~=not-prose] *)) {
    @apply mt-0;
}
```

(replying from my phone, not sure if it would work)

---
https://github.com/CleverCloud/documentation/issues/183
