### ISSUE TITLE
Feature Request: Folder name with no _index should not direct to empty page. Show subpages instead

### ISSUE THREAD

**Issue by Visual-Dawg** [imfing/hextra#293]
**Feature Description**

Currently when a folder has no `_index.md` and you click on its name in the sidebar, you get redirected to a blank article page.

**Problem/Solution**

Either only toggle the collapse, or direct to the first item of the list, or automatically list the subpages. I like the latter the most.

**Alternatives Considered**

Adding an `_index.md` to all folders. However, they need to be maintained and kept up to date when their purpose is to link to the subpages.

**Comment by Visual-Dawg** [comment]
Now that I think about it: It might be better UX if the folder name only toggles the list and is not a link to a site itself, as this can be unexpected and makes it harder to find the data you are looking for (or clicking on it just list the subpages)

**Comment by imfing** [comment]
> Currently when a folder has no _index.md and you click on its name in the sidebar, you get redirected to a blank article page.

Hi, can you provide more details on how to reproduce this?

**Comment by Visual-Dawg** [comment]
This is weird. I cloned the Hextra template, removed the `_index.md` from `folder` and it works as expected. 

Whereas with the files from https://github.com/visual-dawg/hyprland-wiki it creates odd behaviour. Not sure why though. 
I will clone its contents into the starter repo and see if maybe my setup was simply wrong

**Comment by Visual-Dawg** [comment]
I created a reproducible repo using the start template here: https://github.com/Visual-Dawg/hextra-bug-report/tree/main

**Comment by imfing** [comment]
thanks, will look into it 👍

**Comment by Visual-Dawg** [comment]
Thank you! Also a huge thanks for creating this theme. It is *by far* the best looking theme for Hugo out there

**Comment by AndyRaphael** [comment]
Hello
I am also interested in this. I tried to create a custom view by adding a list.html to the layouts/blog folder and copied the content from the hextra\layouts\blog\list.html file. However, this causes the page to render incorrectly. all the content is displayed one another. Instead of "sidebar | content | toc", it shows
"Sidebar
toc
content"

**Comment by imfing** [comment]
@AndyRaphael 

> I tried to create a custom view by adding a list.html to the layouts/blog folder and copied the content from the hextra\layouts\blog\list.html file. However, this causes the page to render incorrectly. all the content is displayed one another. Instead of "sidebar | content | toc", it shows
"Sidebar
toc
content"

regarding this, can you open a separate discussion?

**Comment by AndyRaphael** [comment]
Thank you for your great looking template. Looking forward to this update to show folder content automatically.

**Comment by imfing** [comment]
@Visual-Dawg 

> I created a reproducible repo using the start template here: https://github.com/Visual-Dawg/hextra-bug-report/tree/main

This should be fixed by #325 

but I guess you've added `_index.md` to every sub-directories already :)

**Comment by Visual-Dawg** [comment]
Nice, thank you! Yes, we did, but good to know for the future :D
