### ISSUE TITLE
Indented callouts rendered incorrectly

### ISSUE THREAD

**Issue by AlekseiAdamov** [imfing/hextra#315]
**Description**

Callouts with indentation (e.g. in lists) are rendered incorrectly.

**Steps To Reproduce**

1.  Create a list.
2.  In a list item put a callout with the same indentation as the item's text.

**Expected Behavior**

Callout is rendered correctly.

**Actual Behavior**

Callout is rendered incorrectly.

**Screenshots**

![indented-callout](https://github.com/imfing/hextra/assets/74925431/4fd6ec5d-3719-43b6-829a-bae823694aa6)

Markdown code for this screenshot:

```markdown
## Normal callout

{{< callout emoji="👷‍♂️" >}}
  Work in progress.
{{< /callout >}}

## Indented callout

- List item 1

  {{< callout emoji="👷‍♂️" >}}
    Work in progress.
  {{< /callout >}}

- List item 2
```

**Environment**

- Hugo Version: 0.120.4
- Browser/OS: Chrome 122.0.6261.95/Windows, Edge 122.0.2365.66/Windows
- Theme Version: v0.7.0

**Additional Context**

I see #140 and PR #141 but it was before v0.7.0.

**Comment by imfing** [comment]
Can you post the raw markdown code to reproduce the issue?

**Comment by AlekseiAdamov** [comment]
> Can you post the raw markdown code to reproduce the issue?

Sorry, updated the issue.

**Comment by AlekseiAdamov** [comment]
Great! Thank you!

**Comment by imfing** [comment]
Please wait for the next release to include this fix
