### ISSUE TITLE
can not see the copy button when hover

### ISSUE THREAD

**Issue by loenvom** [imfing/hextra#321]
**Description**

Can not see the copy button when hover.
![image](https://github.com/imfing/hextra/assets/59039948/83b43afb-f59a-4842-b977-d1b466df6a25)
I checked the CSS declaration and it looks like the copy button should appear on hover, but it doesn't. I don't know if it's just me having this issue.

**Steps To Reproduce**

1. open a page of hextra, like https://imfing.github.io/hextra/docs/guide/shortcodes/callout/#default.
2. check the code part.
3. move mouse cursor on the copy button.

**Expected Behavior**

display the copy button.

**Actual Behavior**

the copy button doesn't appear. 

**Screenshots**

**Environment**

- Browser/OS: [e.g., Chrome, Windows]
- Theme Version: [e.g., v0.7.3]

**Comment by imfing** [comment]
I guess it's a bug introduced in https://github.com/imfing/hextra/pull/300

**Comment by imfing** [comment]
Thanks for looking into it. #323 should address this issue
