### ISSUE TITLE
Request for Conversion of Hextra to WordPress Theme

### ISSUE THREAD

**Issue by Hari-Bonda** [imfing/hextra#349]
Hi there,

I hope this message finds you well. I'm reaching out because I'm interested in hiring someone to convert the Hextra theme into a fully functional WordPress theme. I've been impressed by the design and features of the Hextra theme and believe it would be a great fit for my WordPress website.

If you have experience with theme conversion and are confident in your ability to deliver a high-quality WordPress theme based on Hextra, I'd love to discuss this opportunity further. Please let me know your availability and rates for this gig.

Looking forward to hearing from you soon.

Best regards,
Hari

**Comment by imfing** [comment]
Hi Hari,

thank you for reaching out and your interest in converting the Hextra theme for WordPress.

GitHub issues are meant for development purposes like reporting bugs or suggesting improvements.
For hiring requests, I recommend using platforms designed for such tasks. those sites can connect you with professionals skilled in WordPress.

Best of luck with your project
