### ISSUE TITLE
The steps shortcode is not working

### ISSUE THREAD

**Issue by huaxuyu** [imfing/hextra#363]
Hi,

It's a fantastic framework! I just encountered a problem that the steps shortcode is not working: the number of each step including the tree is not shown.

Thanks for your help!

**Comment by imfing** [comment]
Hi could you provide more details on how to reproduce this issue?

**Comment by huaxuyu** [comment]
Thanks for your reply. I simply copied the code from your demo site:

{{% steps %}}

### Step 1

This is the first step.

### Step 2

This is the second step.

{{% /steps %}}

and how the page looks like:
![image](https://github.com/imfing/hextra/assets/90286901/c77dbe6a-e9e9-469e-834e-b50e5f095a5f)

**Comment by huaxuyu** [comment]
Callout and cards work well btw. Other than steps, the "details"  shortcode is not working too. The "details" item fails to render and does not appear on the website.

**Comment by imfing** [comment]
@huaxuyu Hi, could you please verify if these fields are correctly configured in the configuration file (﻿`hugo.yaml`) on your site?

https://github.com/imfing/hextra-starter-template/blob/8b01a6808d25f6a824d6bd2ea67bbe599770171e/hugo.yaml#L9-L17

**Comment by huaxuyu** [comment]
Thank you so much! It's been fixed. I don't have this block in my configuration file.
