### ISSUE TITLE
Expanding the browser window keeps the footer hidden

### ISSUE THREAD

**Issue by fmunteanu** [imfing/hextra#386]
**Description**

Hi @imfing,

I noticed this bug: expanding the browser window keeps the footer hidden.

**Expected Behavior**

Footer should display automatically, on expanded window.

**Actual Behavior**

Only if I scroll down on expanded window, to footer displays.

**Screenshots**

Normal window:

![image](https://github.com/imfing/hextra/assets/19806136/51f5de63-d0c1-472d-96b8-c471882406e6)

Expanded window, with footer hidden:

![image](https://github.com/imfing/hextra/assets/19806136/7d9487d1-1abf-4079-bb58-809716b1d4e4)

Scrolling down, displays the footer:

![image](https://github.com/imfing/hextra/assets/19806136/41ce984a-69cf-4743-a0dd-b34ef3c2a40c)

**Environment**

- Hugo Version: v0.125.4+extended
- Browser/OS: MacOS Firefox
- Theme Version: v0.7.4-0.20240428103006-ba7707d4d9f9

**Comment by imfing** [comment]
@fmunteanu this is intended. If you need to disable this, I think removing the class `hx-min-h-[calc(100vh-var(--navbar-height))]` (you may need to override the layout), or overriding the CSS rule would help.

![image](https://github.com/imfing/hextra/assets/5097752/db58d21a-a4b4-440e-aa2e-e2e8954b0213)

**Comment by fmunteanu** [comment]
Have you had a chance to look at #387 and #388? I hope they can make it in 0.7.4 release.
