### ISSUE TITLE
Make selected entry in sidebar always visible

### ISSUE THREAD

**Issue by fufexan** [imfing/hextra#395]
**Feature Description**

Currently, for sidebars with expanded menus or with more entries than are visible in the viewport, selecting an entry below the viewport doesn't scroll the sidebar accordingly. Thus, the users have to scroll again if they want to see the current selected entry.

The sidebar could have the current selected entry either scrolled to the top, or scrolled to the middle.

**Problem/Solution**

My current problem is that https://wiki.hyprland.org uses expanded menus, which make the sidebar larger than the viewport. This is mostly fine, until you get to the lower entries in the sidebar, such as https://wiki.hyprland.org/Hypr-Ecosystem/. If you click on the link, you can see that the sidebar isn't scrolled to have the selected entry within view.

**Alternatives Considered**

I have considered not having the menus open at all, but after an internal discussion we decided to keep the behavior as is, due to users having a harder time reading the docs when needing to click more menus.

**Additional Context**

How the sidebar currently works:
![image](https://github.com/imfing/hextra/assets/36706276/56b96207-7e96-4e1e-8d69-281b25988974)

How it should work instead:
![image](https://github.com/imfing/hextra/assets/36706276/67ae5117-20fe-40f3-b032-61a5a662a2f5)

**Comment by imfing** [comment]
Thank you for the detailed write-up. Indeed, this can be quite annoying when the sidebar becomes very long. 

I'll look into adding a script that automatically scrolls the active sidebar item into view when the page is visited.
