### ISSUE TITLE
Usage of additional module breaks certain Hextra features

### ISSUE THREAD

**Issue by fmunteanu** [imfing/hextra#399]
**Description**

My website has a specific design pattern, I'm using what I call a `projects` design, linked to specific repositories:

- `/docs`, generates the https://axivo.com frontpage and soon to be implemented tutorials, linked to https://github.com/axivo/website repo
- `/k3s-cluster`, generates the https://axivo.com/k3s-cluster project, linked to https://github.com/axivo/k3s-cluster repo

The [module](https://github.com/axivo/website/blob/fb5d5e9f0ae0b51677c0da3e5cf0297aaa33c5d9/go.mod) uses the same logic you have implemented in your repository, it allows me to store into it all common elements present into each project, `hugo.yaml`, `i18n`, `layouts`, etc. This way, I can customize each project settings, without duplicating the settings or other customized theme elements. Right now I only use 2 projects, but I expect to have at least 15. Imagine the nightmare of maintaining the settings in each project, if I don't eliminate the duplication.

Please see the actual [module implementation](https://github.com/axivo/website/blob/fb5d5e9f0ae0b51677c0da3e5cf0297aaa33c5d9/docs/hugo.yaml#L24).

**Steps To Reproduce**

1. Clone the [repo](https://github.com/axivo/website)
2. Switch to `feature/tutorials` branch
3. Start the server

```
cd docs
hugo server --buildDrafts --disableFastRender --logLevel debug
```

**Expected Behavior**

The front-page should display correctly the `hextra-home` elements (e.g. `hextra/hero-badge`).

**Actual Behavior**

As soon as HTML elements are used inside `hextra/hero-badge`, things break.

```
{{< hextra/hero-badge >}}
  <div class="hx-w-2 hx-h-2 hx-rounded-full hx-bg-primary-400"></div>
  <span>Contribute</span>
  {{< icon name="arrow-circle-right" attributes="height=14" >}}
{{< /hextra/hero-badge >}}
```

Try removing the `div` and `{{< icon >}}`, the code will display.

```
{{< hextra/hero-badge >}}
  <span>Contribute</span>
{{< /hextra/hero-badge >}}
```

**Environment**

- Hugo Version: v0.126.1
- Browser/OS: Safari, MacOS
- Theme Version: v0.7.4-0.20240523223646-d43ac6649463 (curent main branch)

**Additional Context**

@imfing, we we're talking about the mobile browser spacing into #389. That is because I was forced to temporarily move the `hextra/hero-section` inside `hextra/hero-container`, otherwise the text becomes **invisible**.

Try this, move the section outside `/hextra/hero-container`, the text will vanish.

https://github.com/axivo/website/blob/fb5d5e9f0ae0b51677c0da3e5cf0297aaa33c5d9/docs/content/_index.md?plain=1#L37C1-L41C7

Another issue I noticed is: two shortcodes are broken, out of all seven tested. Visit the Tutorials page, to see clearly the issue:
http://localhost:1313/tutorials/

**Comment by fmunteanu** [comment]
@imfing I had to revert the `website` module [implementation](https://github.com/axivo/website/pull/60), in order to fix the broken website. As expected, the issues are gone, but for myself, this a quite a serious bug because the large amount of code duplication I will face soon with the new projects I plan to release.

The mobile browser spacing issue we talked about is also fixed, with the revert.

![IMG_8727](https://github.com/imfing/hextra/assets/19806136/ca4f12ed-76f5-42af-8e97-bcecf0295541)

**Comment by imfing** [comment]
Not a theme bug, nor it's related to modules. It's caused by the split hugo config. 

The top level [hugo.yaml](https://github.com/axivo/website/blob/main/hugo.yaml) was not included when you run `hugo server` under the `docs`, thus the markup configurations were missing. 

try put the `--config` as you did at 
https://github.com/imfing/hextra/discussions/396#discussioncomment-9527854

**Comment by fmunteanu** [comment]
@imfing you are right, I still need to find a solution to avoid passing the `--config` parameter.

**Comment by fmunteanu** [comment]
@imfing I'm reopening the issue, as I determined this is clearly a theme related issue. Please read the Hugo [discussion thread](https://discourse.gohugo.io/t/community-help-to-confirm-my-website-module-is-configured-properly/49996/8), for more details.

**Comment by fmunteanu** [comment]
@imfing, the issue is addressed by setting the into `hugo.yaml`, see [related PR](https://github.com/axivo/website/pull/100). I'm going to leave the issue open, so you update things on your side also. Please close it when is convenient for you.
