### ISSUE TITLE
Allow text in cards to be longer than 3 lines

### ISSUE THREAD

**Issue by kaelemc** [imfing/hextra#420]
Currently text in the card component is clamped to 3 lines with the tailwind class `hx-line-clamp-3`

For some cards the text may be longer than 3 lines. This currently gets truncated and the text is not visible. The easy fix is to remove `hx-line-clamp-3`, but I assume this is not the desired fix.

Not sure how to approach this, possibly allowing the subtitle CSS to be overridden by the user?, or an `overflow` field which can be true (`hx-line-clamp-3`) or false (`hx-line-clamp-none`).

**Comment by imfing** [comment]
try override `layouts/partials/shortcodes/card.html` in your site

**Comment by kaelemc** [comment]
Thanks 👍
