### ISSUE TITLE
Sidebar menu is missing on screen > 768px 

### ISSUE THREAD

**Issue by William-LP** [imfing/hextra#425]
**Description**

The left sidebar menu is missing on larger screen devices when having the following directory structure  :

```
.
├── content
│   ├── _index.md
│   ├── something
│   │   ├── _index.md
│   │   ├── whatever.md
│   ├── foo.md
│   ├── bar.md
```

Note that I'm not using top level directory section like **blog** or **docs**.

**Steps To Reproduce**

1.  Create a new site
2.  Create the same directory structure as above
3.  Play with screen size to make the left sidebar appear and disappear

**Expected Behavior**

The left sidebar should be present on larger screen

**Actual Behavior**

There's no menu on larger screen, but the menu exist on smaller screen

**Screenshots**

[screen-capture.webm](https://github.com/imfing/hextra/assets/10053686/aa1377dd-6257-461f-b058-352776bed44e)

**Environment**

- Hugo Version: **hugo v0.128.2-de36c1a95d28595d8243fd8b891665b069ed0850+extended linux/amd64 BuildDate=2024-07-04T08:13:25Z VendorInfo=gohugoio**
- Browser/OS: Chrome
- Theme Version: latest

**Additional Context**

Let me know if you need more context or information

**Comment by imfing** [comment]
Can you try setting the type of the section to `docs`

https://imfing.github.io/hextra/docs/guide/organize-files/#layouts

**Comment by 880831ian** [comment]
@imfing 

Hi, I would like to ask by the way, I want to use blog type but want to enable sidebar, what should I do?

I need to create layouts/blog/single.html yourself and adjust `{{ partial "sidebar.html" (dict "context" . "disableSidebar" true "displayPlaceholder" true) }}` ?

**Comment by William-LP** [comment]
@imfing Thanks it works as expected !

**Comment by imfing** [comment]
> @imfing 
> 
> 
> 
> Hi, I would like to ask by the way, I want to use blog type but want to enable sidebar, what should I do?
> 
> 
> 
> I need to create layouts/blog/single.html yourself and adjust `{{ partial "sidebar.html" (dict "context" . "disableSidebar" true "displayPlaceholder" true) }}` ?
> 
> 
> 
> I currently use docs with a sidebar, but I want to display the date and creation time like a blog. How should I do this?

@880831ian hi this is not supported currently. you have to override the blog page template to include sidebar
