### ISSUE TITLE
Callout in Tab don't work

### ISSUE THREAD

**Issue by William-LP** [imfing/hextra#429]
**Description**

When using a `callout` within a `tab` shortcode, the callout does not get displayed.

**Steps To Reproduce**

Create a page with the following code :

```markdown
{{< tabs items="foo,bar" >}}

  {{< tab >}}
    This is displayed
      {{< callout >}}
      This is not displayed
      {{< /callout >}}
    This is also displayed

  {{< /tab >}}

  {{< tab >}}
    This is displayed
      {{< callout type="info">}}
      This is not displayed
      {{< /callout >}}
    This is also displayed
  {{< /tab >}}

{{< /tabs >}}
```

**Expected Behavior**

The callout should render inside the tab

**Actual Behavior**

The callout is not displayed in the tab. Everything before and after the callout render properly.

**Screenshots**

![image](https://github.com/user-attachments/assets/7fe3b421-2f2d-453f-9066-3c1679920411)

**Environment**

- Hugo Version: hugo v0.128.2-de36c1a95d28595d8243fd8b891665b069ed0850+extended linux/amd64 BuildDate=2024-07-04T08:13:25Z VendorInfo=gohugoio
- Browser/OS: Chrome
- Theme Version: latest

**Comment by imfing** [comment]
@William-LP did you have the `markup` field set like this?
https://github.com/imfing/hextra-starter-template/blob/9d4fdefc0d36e6f2f7f4e90b23a791a0db7fa9e6/hugo.yaml#L9-L17

**Comment by William-LP** [comment]
@imfing : it now works when adding this configuration, thank you !
