### ISSUE TITLE
Automatically use cards in docs/list.html template

### ISSUE THREAD

**Issue by MattDodsonEnglish** [imfing/hextra#439]
**Feature Description**

For each list page (that is, the `_index.md`), a template could use cards to list the contents within. This would automate what the example site [currently does manually](https://github.com/imfing/hextra/blob/852a07b15ea1910e300b6cb341dfcb0a7e03c3a8/exampleSite/content/docs/guide/_index.md).

The generated "cards" menu could even add extra info from the pages frontmatter, like `description` or `icon`.

**Problem/Solution**

List pages show up as blank and they are clickable from the sidebar. This creates literal gaps in the reading experience.

As linked, the author can use cards to make their own menu, which is nice for discovery. But this needs to be manually maintained each time the sidebar changes.

**Alternatives Considered**

Have a parameter to make _index pages inaccessible. That is, clicking the page name in the sidebar would just expand to show it's contents within.

**Comment by imfing** [comment]
Thanks for the proposal. I think a feasible way is to create a custom shortcode to implement such grouping for these cards. 

- [Create your own shortcodes | Hugo](https://gohugo.io/templates/shortcode/)

**Comment by MattDodsonEnglish** [comment]
Thanks, the shortcode worked well, especially since  there already is a Card partial that I could re-use in the shortcode. 

Here is `card-list.html`: 

```go
{{ .Scratch.Set "pages" .Page.Pages }}
{{ $pages := (.Scratch.Get "pages") }}

<div class="hextra-cards hx-mt-4 hx-gap-4 hx-grid not-prose"
     style="--hextra-cards-grid-cols: 2;">

{{template "childs" (dict "menu" $pages.ByWeight "pages" .Site.Pages) }}

</div>

{{ define "childs" }}
    {{ range .menu }}
    {{ $icon := .Page.Params.icon }}
    {{ $tags := .Page.Params.tags }}
    {{ partial "shortcodes/card.html" (dict
        "link" .RelPermalink
        "title" .Title
        "subtitle" .Description
        "icon" $icon
        "tag" $tags
    )}}
    {{end}}
{{end}}
```

![image](https://github.com/user-attachments/assets/3c26b5bf-ba16-4ebb-b33d-002fcd9b8a74)

To list the child pages, I did a huge simplification of how I understand the logic from the old [Hugo Learn `children` shortcode](https://github.com/matcornic/hugo-theme-learn/blob/master/layouts/shortcodes/children.html).  I'm using page params for icons, and using `cascade` to set a global icon for a certain section.

This works fine for me. The only issue I see is that it'll go out of date if the hextra CSS selectors for the cards change some day. So please use or modify it if it suits you; I'd rather use the theme's built-ins than have some customization.  But this does all I need to do.

**Comment by BabakScript** [comment]
Hi @imfing I tried to customize/overwrite the default Hextra list page based on @MattDodsonEnglish code and put my code in `/layouts/_default/list.html` but it seems it's not working. Any idea?

**Comment by imfing** [comment]
> Hi @imfing I tried to customize/overwrite the default Hextra list page based on @MattDodsonEnglish code and put my code in `/layouts/_default/list.html` but it seems it's not working. Any idea?

Hi the above snippet is for shortcodes, to customize you need to copy the list.html under the same path in this repo and make changes respectively
