### ISSUE TITLE
Tags shortcode / partial

### ISSUE THREAD

**Issue by benbarbour** [imfing/hextra#455]
**Feature Description**

I like the little tag pills on cards and want to use them elsewhere. I can (and did) copy/paste some of the code to make my own, but it might be nice if it was built into the theme.

**Problem/Solution**

It'll let me add little tag pills to my content easily.

**Alternatives Considered**

I have made my own.

**Comment by imfing** [comment]
good idea

**Comment by juliamrch** [comment]
My baby tag pill really is going places 🥹
