### ISSUE TITLE
[Feature Request] Allow to disable sidebar along with placeholder empty space.

### ISSUE THREAD

**Issue by nisrulz** [imfing/hextra#466]
When setting up as a blog, the pages could make use of empty sidebar area to fit more content onscreen.

When I search in codebase, [I can find some variable that will allow to do](https://github.com/search?q=repo%3Aimfing%2Fhextra%20disableSidebar&type=code) so, but I cannot change it via the config file.

This makes sense only in the case TOC is visible, otherwise the empty space is desired as without TOC the page will then need to be centered.

Incase TOC shows up, the sidebar placeholder empty space should be removed/hidden.

<img width="600" alt="Screenshot 2024-09-30 at 23 14 24" src="https://github.com/user-attachments/assets/0867280e-c5d5-46bc-a5be-9bb48970a60a">

**Comment by nisrulz** [comment]
I was able to override the implementation by duplicating the `layout/blog/single.html` and changing the line from

```
    {{ partial "sidebar.html" (dict "context" . "disableSidebar" true "displayPlaceholder" true) }}
```

to

```
    {{ partial "sidebar.html" (dict "context" . "disableSidebar" true "displayPlaceholder" false) }}
```

Would be nice if this can be done via the config somehow. Maybe in the page itself on demand, like we can do for `toc`.

**Comment by imfing** [comment]
> When I search in codebase, I can find some variable that will allow to do so, but I cannot change it via the config file.

feel free to override the default layout where you could specify different variable 

https://imfing.github.io/hextra/docs/advanced/customization/#custom-layouts
