### ISSUE TITLE
The README file in Simplified Chinese seems to have translation errors

### ISSUE THREAD

**Issue by Dev-Huang1** [imfing/hextra#468]
**Description**

The README file in Simplified Chinese has a translation error in the "网站中的瑞士军刀" under "特征"

Here, you translated the "Battery-included" in the English README file into the Chinese README file "网站中的瑞士军刀" (the Swiss Army Knife of the website)

**Screenshots**

![Screenshot_20241006_132309](https://github.com/user-attachments/assets/0a6525d2-4d1b-45c4-9793-5d1bcfcf0055)

**Comment by imfing** [comment]
@Dev-Huang1 can you send a quick Pull Request?

**Comment by Dev-Huang1** [comment]
See pull request [#475](https://github.com/imfing/pull/475)
