### ISSUE TITLE
Question(about perf): Why keep tocs that don't need to be displayed?

### ISSUE THREAD

**Issue by potoo0** [imfing/hextra#485]
Source: [sidebar#L25-L29](https://github.com/imfing/hextra/blob/main/layouts/partials/sidebar.html#L25-L29)

Such as, the blog don't need the document toc.
For your demo site: [blog](https://imfing.github.io/hextra/blog/)

![image](https://github.com/user-attachments/assets/0afc2bb2-120e-4a0d-842a-da9ce11eb15c)
(figure 1)

**Comment by imfing** [comment]
it's for the mobile navigation bar


if you shrink the window width you should see it
