### ISSUE TITLE
Setting displayCopyright to "False" does not remove copyright, user should have option to customize copyright

### ISSUE THREAD

**Issue by mdavistffhrtporg** [imfing/hextra#494]
**Description**

setting:

  footer:
    enable: true
    displayCopyright: false
    displayPoweredBy: false
    width: normal

in hugo.yaml does not take effect.

Additionally, the user should have the option to customize the copyright text. Hextra does not own the content that the end user see's, therefore there should be the option to have it customized so that the text display to the end user displays the owner's name, eg (c) 2023-2023 Matthew A. Davis BY-SA 4.0

**Steps To Reproduce**

1. set display displayCopyright: false
2.  observe hextra copyright displayed on site

https://docs.fhrp.org/

**Expected Behavior**

Copyright should not have been displayed or I should be able to customize the copyright text.

**Actual Behavior**

Copyright was displayed and I cannot customize the text.

**Comment by imfing** [comment]
> in hugo.yaml does not take effect.

can't reproduce the issue on my end. the exact setting `displayCopyright: false` is set in the starter template:

https://github.com/imfing/hextra-starter-template/blob/86c4d9e80f25016dfd85194da3a98210e15ba1ea/hugo.yaml#L50-L51

and the copyright text is not shown in the starter template site: https://imfing.github.io/hextra-starter-template/

> Additionally, the user should have the option to customize the copyright text. 

Please take a look at https://imfing.github.io/hextra/docs/guide/configuration/#copyright

**Comment by kdrozd** [comment]
I think confusions may come from the fact that there are two places that describe how to update copyright information in the footer.

There is https://imfing.github.io/hextra/docs/advanced/customization/#custom-footer-section which is not working as intended when user would like to change copyright name and then there is https://imfing.github.io/hextra/docs/guide/configuration/#copyright which actually works.

I found myself in the same situation as @mdavistffhrtporg, so it would be good to clarify documentation and examples to make it easier for users of the theme.

**Comment by imfing** [comment]
> There is https://imfing.github.io/hextra/docs/advanced/customization/#custom-footer-section which is not working as intended

This section was added yesterday. I'll update it for more clarity.

**Comment by imfing** [comment]
@kdrozd updated in https://github.com/imfing/hextra/commit/cf61e606c150495d7189ea160a90c9579dacdcd5

now it should cause fewer confusions
