### ISSUE TITLE
How did you get the sidebar to always be present in docs?

### ISSUE THREAD

**Issue by JoshDPT** [imfing/hextra#496]
**Feature Description**

In docs, section of Hextra docs, the sidebar is always present and static

**Problem/Solution**

When I try to implement this - with:

```
cascade:
  type: docs
```

It is still shrinking as I go deeper in the tree

Any guidance on what I am missing to keep the left sidebar static as I go to a page? TIA!

**Comment by imfing** [comment]
can you check this setting in the frontmatter?

https://github.com/imfing/hextra/blob/4c4f43779c6de5adf1c61edd4e79aae233965393/exampleSite/content/docs/guide/_index.md?plain=1#L7

**Comment by JoshDPT** [comment]
@imfing - thank you so much! I thought I tried that - but when I added it to every level - it did the trick. Thanks again for the fast response!

**Comment by imfing** [comment]
> @imfing - thank you so much! I thought I tried that - but when I added it to every level - it did the trick. Thanks again for the fast response!
> 
> 

you are welcome 😄
