### ISSUE TITLE
Missing value of integrity attribute 

### ISSUE THREAD

**Issue by hugo-sid** [imfing/hextra#5]
## Steps to reproduce
View the source of any page. 

You can see that, in the `<head>` tag, the value of integrity attribute is missing for external stylesheets (`<link />` tags):

For example, on [this page](https://imfing.github.io/hextra/docs/guide/markdown/) I observed that:
```html
<link href="/hextra/css/compiled/main.min.ecc9bbfeacf5a6f4e36c4a8ef28ad870def480b01c4126a5fb3f7fe92c9fb3a3.css" rel=stylesheet integrity>
<link href=/hextra/css/custom.min.e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css rel=stylesheet integrity>
```

**Comment by imfing** [comment]
Good catch again, thanks! It's a mis-spelling in the head template

https://github.com/imfing/hextra/blob/57134eae361effa32f80e56f0136814de95ff433/layouts/partials/head-css.html#L9

Should capitalize the `integrity`: `.Data.Integrity`
