### ISSUE TITLE
 Cannot apply tailwind CSS styles in Hextra

### ISSUE THREAD

**Issue by renardeinside** [imfing/hextra#500]
**Description**

Hi, I I'm wondering whenever it's possible to apply tailwindcss classes in Hextra, considerting Hextra already uses it?

**Steps To Reproduce**

Currently when I'm passing the classes they're not getting applied really:
```
# layouts/index.html

{{ define "main" }}
    <div class="flex h-screen w-screen">
        <h2 class="font-bold text-2xl">My cool string goes on here</h2>
    </div>
{{ .Content }}
{{ end }}

```

**What should have happened?**

Classes are applied

** What happened instead? **

Classes are not applied

**Environment**

```
>  hugo          
Start building sites … 
hugo v0.138.0+extended+withdeploy darwin/arm64 BuildDate=2024-11-06T11:22:34Z VendorInfo=brew
```

**Comment by imfing** [comment]
Please take a look at the discussion here:

https://github.com/imfing/hextra/discussions/111

Hextra leverages Tailwind CSS only during the development process. Please include Tailwind CSS in your own project appropriately.

**Comment by renardeinside** [comment]
Hi @imfing ,
thanks a lot, now I've understood how to do this 😅
