### ISSUE TITLE
add Font 

### ISSUE THREAD

**Issue by MahdiButcher** [imfing/hextra#501]
**Feature Description**

fonts for persian people

**Problem/Solution**

hey @imfing. the VazirMatn is a iconic font in Iran because the writer passed away in a tragedy. so choosing this font is very good decision. I think adding a choosing font inside the hugo.yaml is not a bad Idea instead of custom.css, and using a googlefontapi is very good, their cdn font is way better than local storage. a lots of sites around the world used google fonts . so please get this a go

**Alternatives Considered**

nothing

**Additional Context**

nothing

**Comment by imfing** [comment]
the font is available on google fonts so you can use it through the [custom CSS](https://imfing.github.io/hextra/docs/advanced/customization/#custom-css)

https://fonts.google.com/specimen/Vazirmatn

**Comment by MahdiButcher** [comment]
> the font is available on google fonts so you can use it through the [custom CSS](https://imfing.github.io/hextra/docs/advanced/customization/#custom-css)
> 
> [fonts.google.com/specimen/Vazirmatn](https://fonts.google.com/specimen/Vazirmatn)

the problem is if i use .content, the footer and header doesn't apply the font. if i use * , i think it's dangerous? so what i'm done is I use .content and a to set the font and it worked. maybe a little docs over setting font is good?

**Comment by MahdiButcher** [comment]
it is in my repo 
https://github.com/MahdiButcher/mahdibutcher.github.io/blob/main/assets/css/custom.css

i didn't apply the language fonts , so there is a flaw. if you clearify the best way to add fonts, i will document it and add a new page to the document site

**Comment by imfing** [comment]
> > the font is available on google fonts so you can use it through the [custom CSS](https://imfing.github.io/hextra/docs/advanced/customization/#custom-css)
> 
> > 
> 
> > [fonts.google.com/specimen/Vazirmatn](https://fonts.google.com/specimen/Vazirmatn)
> 
> 
> 
> the problem is if i use .content, the footer and header doesn't apply the font. if i use * , i think it's dangerous? so what i'm done is I use .content and a to set the font and it worked. maybe a little docs over setting font is good?

use the body specifier

https://www.w3schools.com/css/css_font_google.asp

**Comment by happybigboy** [comment]
> > > the font is available on google fonts so you can use it through the [custom CSS](https://imfing.github.io/hextra/docs/advanced/customization/#custom-css)
> > 
> > 
> > > 
> > 
> > 
> > > [fonts.google.com/specimen/Vazirmatn](https://fonts.google.com/specimen/Vazirmatn)
> > 
> > 
> > the problem is if i use .content, the footer and header doesn't apply the font. if i use * , i think it's dangerous? so what i'm done is I use .content and a to set the font and it worked. maybe a little docs over setting font is good?
> 
> use the body specifier
> 
> [w3schools.com/css/css_font_google.asp](https://www.w3schools.com/css/css_font_google.asp)

I can make a document about this for font. how about now?

**Comment by happybigboy** [comment]
oops , another account 🤣

**Comment by MahdiButcher** [comment]
okay. I will make a document and pull it to doc
