### ISSUE TITLE
Add giscus custom theme

### ISSUE THREAD

**Issue by ywonchae1** [imfing/hextra#521]
**Feature Description**

There was no option for setting giscus theme. So I added a feature to be able to set giscus theme by `hugo.yaml` file for customization.

**Problem/Solution**

Problem:
Just toggled `light` or `dark`. These options originally using for Hextra light/dark theme.

Solution:
giscus has pair of themes. (e.g. `noborder_light`, `noborder_dark`)

<img width="294" alt="Screenshot 2024-12-22 at 01 24 57" src="https://github.com/user-attachments/assets/6b786896-768d-4a21-b6df-8386397907a2" />

Finding out `current theme` of Hextra, and then replacing `light` to `dark` in the string could be the solution.

Also, I add an option to `hugo.yaml` file so that users could custom giscus theme easily.

```yaml
params:
  comments:
    giscus:
      theme: noborder_light
```

**Comment by imfing** [comment]
completed in #522
