### ISSUE TITLE
[BUG] Hide the color of the tabs

### ISSUE THREAD

**Issue by erfjab** [imfing/hextra#524]
https://github.com/user-attachments/assets/883d49f2-160b-412b-8d8d-e84a9fed419c

When I choose the latter, the color is removed.

**Comment by imfing** [comment]
@erfjab can you provide an example file or section that can reproduce this issue?

**Comment by erfjab** [comment]
Yes, live example is here: https://marzneshinscommunity.github.io/doc/docs/marzneshin/ssl/

**Comment by erfjab** [comment]
Thank you so much ❤️
