### ISSUE TITLE
Supports hiding the top navigation panel or the footer panel

### ISSUE THREAD

**Issue by Leroy-X** [imfing/hextra#60]
Hello, I just started trying to use hugo to write documents. I discovered the Hextra theme, which is very lightweight and even supports Chinese search. I like it very much.

I have some questions. as follows:
How to customize the configuration to hide the navigation at the top of the page or the panel at the footer? Just like the [book theme](https://themes.gohugo.io/themes/hugo-book/). Or modify the height of the bottom panel. The current default is too high and there is a lot of blank space.

By the way, is it possible to increase the size of the dark mode or light mode icons, they are a bit small now and hard to notice in dark mode.

Thank you so much! English is not my first language. I hope you can understand the results of Google Translate.

**Comment by imfing** [comment]
Thank you for choosing the Hextra theme!

> How to customize the configuration to hide the navigation at the top of the page or the panel at the footer? Just like the [book theme](https://themes.gohugo.io/themes/hugo-book/). Or modify the height of the bottom panel. The current default is too high and there is a lot of blank space.

Just similar to [Primary Color](https://imfing.github.io/hextra/docs/advanced/customization/#primary-color), we provide another css variable that allows you to adjust the height of the navbar: `--navbar-height`. You can find it using your browseer's developer tool.
Unfortunately, the navbar and bottom panel style can't be modified without overriding the template or using custom CSS rules. 
For more details about how to use custom CSS, please refer to the [Custom CSS](https://imfing.github.io/hextra/docs/advanced/customization/#custom-css) section. 

> By the way, is it possible to increase the size of the dark mode or light mode icons, they are a bit small now and hard to notice in dark mode.

I can make the icon a bit bigger in the future. As for now, please customize it in using custom CSS rules.

**Comment by Leroy-X** [comment]
Thank you for your reply, have a nice day.
