### ISSUE TITLE
Custom index.html title

### ISSUE THREAD

**Issue by LarsStegman** [imfing/hextra#62]
Hi,

I would like to the replace the default `h1` header on the `index.html` with a custom component. Is it possible to make this a partial so it can be overridden?

Thanks!

**Comment by imfing** [comment]
Hi, you can copy and override the `layouts/index.html` in your own site, where you can put the header what ever you want. 
What do you expect from overriding the `h1`?

**Comment by LarsStegman** [comment]
Oh that's also a good idea, thanks!

I want to put in an animation so it appears someone is typing the title.
