### ISSUE TITLE
Generate full content on RSS instead of only summary

### ISSUE THREAD

**Issue by vinay-keshava** [imfing/hextra#66]
I've used the template repository to create a hugo site and the index.xml doesn't generate full contents it only generates summary 
Help or insight needed on this !

Enable Full Text RSS feed

this is an example site which generates full content which enhances readability in RSS
https://blog.sahilister.in/index.xml

**Comment by imfing** [comment]
it's generating the full content in the RSS feed, for example, the blog section
https://imfing.github.io/hextra/blog/index.xml

and RSS is enabled here in the docs site for sections:
https://github.com/imfing/hextra/blob/c799160e86279ade57033721c9b6698451baf65a/exampleSite/hugo.yaml#L10-L13

**Comment by vinay-keshava** [comment]
![image](https://github.com/imfing/hextra/assets/74909320/e448052a-248b-4a4c-bfe1-0551edc7152a)
i've added the above config to hugo.yaml
still the whole content is not shown on RSS

**Comment by imfing** [comment]
try localhost:1313/blog/index.xml
it should contain the full content RSS feed

**Comment by vinay-keshava** [comment]
i tried it for blog/ and docs/ too

**Comment by imfing** [comment]
I'll look into this. It would be nice if you could share an example repository for reproducing the issue.

**Comment by hugo-sid** [comment]
AFAIK, unless a custom RSS template is used, Hugo includes only a summary of the article in RSS feed. This is due to the `<description>{{ .Summary | html }}</description>` in the [default RSS template](https://github.com/gohugoio/hugo/blob/f9163155d3cffc4cc994735b7ffbba5c561bb7a0/tpl/tplimpl/embedded/templates/_default/rss.xml#L35).

To include the full post content in the feed, a custom RSS template should be defined with `<description>{{ .Content | html }}</description>` (instead of `.Summary`).

INMHO, it's better to provide a switch to control this feature (full post in RSS feed) via one of the config parameters. Here is a PR where this is implemented: https://github.com/hugo-sid/hugo-blog-awesome/pull/113 .

**Comment by imfing** [comment]
> AFAIK, unless a custom RSS template is used, Hugo includes only a summary of the article in RSS feed. This is due to the `<description>{{ .Summary | html }}</description>` in the [default RSS template](https://github.com/gohugoio/hugo/blob/f9163155d3cffc4cc994735b7ffbba5c561bb7a0/tpl/tplimpl/embedded/templates/_default/rss.xml#L35).
> 
> 
> 
> To include the full post content in feed, a custom RSS template should be defined with `.Content` (instead of `.Summary`).
> 
> 
> 
> INMHO, it's better to provide a switch to control this feature (full post in RSS feed) via one of the config parameters. Here is an example where this is implemented: https://github.com/hugo-sid/hugo-blog-awesome/pull/113.

@hugo-sid Thanks for the info. 

FYI, I have implemented full content RSS in `layouts/section/section.rss.xml` for sections like blog, but the contents are not placed in the description tags.

If the OP wants descriptions tag, then the only way is to override the RSS template.

**Comment by hugo-sid** [comment]
Thanks fo the info @imfing.

> FYI, I have implemented full content RSS in `layouts/section/section.rss.xml` for sections like blog, but the contents are not placed in the description tags.

Yes, I saw that just now.

> If the OP wants descriptions tag, then the only way is to override the RSS template.

Agree.

**Comment by imfing** [comment]
> BTW, this is what I see at https://imfing.github.io/hextra/blog/index.xml

@hugo-sid I was aware of this, basically it lacks the `xmlns:content="http://purl.org/rss/1.0/modules/content/"` attribute on `<rss>`

I will create a PR to fix a  couple of things for the RSS feed.

**Comment by hugo-sid** [comment]
> @hugo-sid I've created a PR #75 the RSS feed xml is parsed correctly by the browser now: https://deploy-preview-75--hugo-hextra.netlify.app/blog/index.xml

Great!

**Comment by vinay-keshava** [comment]
Great 
https://github.com/vinay-keshava/blog
this is the link to my site,i've also updated the hugo.yaml to generate rss
but gives a 404

**Comment by imfing** [comment]
Please rename `contents/posts` to `contents/blog`

otherwise access it using `/posts`

**Comment by vinay-keshava** [comment]
> Please rename `contents/posts` to `contents/blog`
> 
> otherwise access it using `/posts`

![image](https://github.com/imfing/hextra/assets/74909320/67d77e4e-6118-43a1-b5c0-dd6df707dc92)

i have renamed it to blog/
now it says
XML Parsing Error: prefix not bound to a namespace
Location: http://localhost:1313/blog/index.xml
Line Number 17, Column 7:

for both blog/index.xml and docs/index.xml

**Comment by vinay-keshava** [comment]
> Can you also update the theme version please?

in go.mod

```
module github.com/imfing/hextra-starter-template

go 1.21

require github.com/imfing/hextra v0.5.0 // indirect
```

**Comment by vinay-keshava** [comment]
> > Can you also update the theme version please?
> 
> in go.mod
> 
> ```
![image](https://github.com/imfing/hextra/assets/74909320/4bb68352-442e-4fc7-9d04-bea225da2902)

after updating the version the theme version docs/ directory generates rss but not blog/
> module github.com/imfing/hextra-starter-template
> 
> go 1.21
> 
> require github.com/imfing/hextra v0.5.0 // indirect
> ```

**Comment by imfing** [comment]
You may need to create a `_index.md` file under the blog section.

Please follow the exampleSite provided in this repository

**Comment by vinay-keshava** [comment]
> You may need to create a `_index.md` file under the blog section.
> 
> Please follow the exampleSite provided in this repository

Its still the same even after adding the _index.md
i've followed the exampleSite in this repository.

**Comment by imfing** [comment]
@vinay-keshava I took a quick look of your repo, there are two issues:

1. Please remove the `type: post` from your blog posts files, it's gonna mess up how Hugo looks up for template. I think this is the main reason why the RSS feed not showing the full content. https://github.com/vinay-keshava/blog/blob/6045e00579d0fad578ac217a40e87ff17eea044b/content/blog/contributing-to-debian.md?plain=1#L6

after remove the frontmatter, the RSS content shows up:
![image](https://github.com/imfing/hextra/assets/5097752/2df34cc0-32bb-468c-a631-f49ed1f84c11)


2. This reference of the next page won't work: https://github.com/vinay-keshava/blog/blob/6045e00579d0fad578ac217a40e87ff17eea044b/content/docs/_index.md?plain=1#L3 it prevents the site from compiling. You need to replace it with `next: blog/interception-vimproved`

**Comment by vinay-keshava** [comment]
@imfing thanks a lot for helping,i was a noob at hugo.
Fixed these issues and it started working

**Comment by imfing** [comment]
@vinay-keshava no problem, this might also help people who may encounter the same problem in the future 😃
