### ISSUE TITLE
Can't insert an image

### ISSUE THREAD

**Issue by vovavasylyna** [imfing/hextra#74]
Hi there! 

Sorry this may be a rookie question but what path I should use to reference the image for it to be added to [my page](https://vovavasylyna.github.io/landusheva/services/services-process/) inside one of the folders? I've tried putting .jpg files to /static/images/ and then referencing as /images/process2.jpg but the image not being added.

I then tried moving images around and referencing different paths but no success so far.

https://github.com/vovavasylyna/landusheva

Best,
Vova

**Comment by imfing** [comment]
Hi @vovavasylyna , please try the following:

1. convert the `/content/services/services-process.md` into a directory, i.e. `/content/services/services-process/`
2. move the `services-process.md` under that directory and rename it to `index.md`: `/content/services/services-process/index.md`
3. move images under the directory: `/content/services/services-process/example.png`
4. reference the image in this way: `![](example.png)`

**Comment by imfing** [comment]
> Sorry this may be a rookie question but what path I should use to reference the image for it to be added to [my page](https://vovavasylyna.github.io/landusheva/services/services-process/) inside one of the folders? I've tried putting .jpg files to /static/images/ and then referencing as /images/process2.jpg but the image not being added.

Thank you for saying that, but actually, the fault was mine. What you tried *should* work, so it's a bug I need to fix. Appreciate for pointing this out 😃

**Comment by vovavasylyna** [comment]
thank you @imfing, it worked!

**Comment by Joshswooft** [comment]
Hi @imfing , 

I'm having a similar issue. 


```
{{< cards >}}
  {{< card link="/explore/rome" title="Rome" image="colisee-rome-920194859.jpg" subtitle="Ancient rome, where emporerors reined and gladiators fought for their freedom." method="Resize" options="600x q80 r90 webp" >}}
  {{< card link="/explore/phuket" title="Phuket" image="phuket-thailand.jpg" subtitle="The amazing archepelos of Thailand" method="Resize" options="600x q80 webp" >}}
  {{< card link="/explore/nusa-penida" title="Nusa Penida" image="../../assets/images/nusa-penida-kelingking.jpg" subtitle="The beautiful island off Bali, come see the breathtaking views." method="Resize" options="600x q80 r90 webp" >}}
{{< /cards >}}
```

I'm trying to get the cards to apply hugo processing on the image to make them into webp files. 

The first 2 images load but they don't apply any of the processing. For the last image I've tried loading it from an asset folder I made but that doesn't seem to work. Despite what it mentions in the docs: https://imfing.github.io/hextra/docs/guide/shortcodes/cards/#image-card

<img width="315" alt="Screenshot 2024-12-27 at 16 24 16" src="https://github.com/user-attachments/assets/cb959a9e-0316-484d-9452-9705a0cab9c4" />


<img width="301" alt="Screenshot 2024-12-27 at 16 23 50" src="https://github.com/user-attachments/assets/b841168f-003d-40f8-92d5-23849a27f7b9" />

**Comment by imfing** [comment]
@Joshswooft please use the relative path under the assets folder


```
image="images/nusa-penida-kelingking.jpg"
```

**Comment by Joshswooft** [comment]
@imfing perfect ty!! :D

**Comment by joelabc** [comment]
@imfing I am facing an issue where I am not able to get the image to load in the card.

<img width="230" height="378" alt="Image" src="https://github.com/user-attachments/assets/48dc731a-adcf-4dac-9454-54ce602c5f12" />

content/gallery/nature/index.md  --> (according to the docs this should be the hierarchy)

```---
title: Nature
next: first-page
type: docs
---

{{< cards cols="2" >}}
{{< card link="/gallery/nature/assorted" title="🗑️ Assorted" >}}
{{< card link="/gallery/nature/spiders" title="🕷️ Spiders" >}}
{{< /cards >}}


{{< cards cols="2" >}}
{{< card link="/" title="Local Image" image="images/1.jpg" subtitle="image" method="Resize" options="600x q80 webp" >}}
{{< card link="/" title="Local Image" image="/content/gallery/nature/1.jpg" subtitle="image" method="Resize" options="600x q80 webp" >}}
{{< /cards >}}
```

<img width="1765" height="442" alt="Image" src="https://github.com/user-attachments/assets/25a9a4ad-929c-43a1-8433-934bf78111ee" />


--> The folder structure shows the setup and I have tried adding the images from both the nested folder as well as the aasets/images folder. I am still not able to get a rendered image. Any help would be much appreciated.

**Comment by imfing** [comment]
> @imfing I am facing an issue where I am not able to get the image to load in the card.
> 
> <img width="230" height="378" alt="Image" src="https://github.com/user-attachments/assets/48dc731a-adcf-4dac-9454-54ce602c5f12" />
> 
> content/gallery/nature/index.md  --> (according to the docs this should be the hierarchy)
> 
> ```---
> title: Nature
> next: first-page
> type: docs
> ---
> 
> {{< cards cols="2" >}}
> {{< card link="/gallery/nature/assorted" title="🗑️ Assorted" >}}
> {{< card link="/gallery/nature/spiders" title="🕷️ Spiders" >}}
> {{< /cards >}}
> 
> 
> {{< cards cols="2" >}}
> {{< card link="/" title="Local Image" image="images/1.jpg" subtitle="image" method="Resize" options="600x q80 webp" >}}
> {{< card link="/" title="Local Image" image="/content/gallery/nature/1.jpg" subtitle="image" method="Resize" options="600x q80 webp" >}}
> {{< /cards >}}
> ```
> 
> <img width="1765" height="442" alt="Image" src="https://github.com/user-attachments/assets/25a9a4ad-929c-43a1-8433-934bf78111ee" />
> 
> 
> --> The folder structure shows the setup and I have tried adding the images from both the nested folder as well as the aasets/images folder. I am still not able to get a rendered image. Any help would be much appreciated.
> 
> 


Please use relative path, and do not prepend "/" slash in the front unless it's under static

Will update the doc to clarify this

**Comment by joelabc** [comment]
```
{{< cards >}}
  {{< card link="/" title="Image Card" image="/images/1.jpg" subtitle="Image" tag="tag text" tagColor="green" >}}
  {{< card link="/" title="Image Card" image="https://unsplash.com/photos/a-close-up-of-a-bunch-of-flowers-in-a-field-861jE8wt1rU" subtitle="Unsplash Landscape" >}}
  {{< card link="/" title="Image Card" image="images/1.jpg" subtitle="Image" tag="tag text" tagColor="purple" tagIcon="sparkles" tagBorder=false >}}
{{< /cards >}}
```

<img width="236" height="664" alt="Image" src="https://github.com/user-attachments/assets/cbee2681-429e-4a93-931e-9b552a75012f" />

I have added 3 types of images, and all 3 are not working. 
1. ```   {{< card link="/" title="Image Card" image="/images/1.jpg" subtitle="Image" tag="tag text" tagColor="green" >}} ``` This image is joelabc\static\images\1.jpg
2. ``` {{< card link="/" title="Image Card" image="https://unsplash.com/photos/a-close-up-of-a-bunch-of-flowers-in-a-field-861jE8wt1rU" subtitle="Unsplash Landscape" >}} ``` This is an image URL
3. ``` {{< card link="/" title="Image Card" image="images/1.jpg" subtitle="Image" tag="tag text" tagColor="purple" tagIcon="sparkles" tagBorder=false >}} ``` This image is joelabc\content\gallery\nature\1.jpg

None of this gives me a render in local. Am I missing something else? Any thoughts @imfing ?

**Comment by imfing** [comment]
@joelabc it errored at "error calling Process: this feature is not available in" 

can you google the full error messages and see if there's any hugo version mismatch?

**Comment by joelabc** [comment]
Classic case of read the error before asking. I found out that my installation of Hugo was not the one compatible with image processing. 

Thanks again for the prompt response.
