### ISSUE TITLE
mac search shortcut symbol on windows

### ISSUE THREAD

**Issue by ludfjig** [imfing/hextra#91]
![image](https://github.com/imfing/hextra/assets/4257730/495fd216-bf59-42a3-bca5-d045b44f51cd)
im on windows but the symbol is a mac only symbol

**Comment by imfing** [comment]
thanks, will fix it

**Comment by imfing** [comment]
@ludfjig it's fixed and the fix will be included in the next release of Hextra. thanks for the feedback to make Hextra better 💪
